FROM golang:1.19 AS build-stage

RUN mkdir /app

ADD . /app

WORKDIR /app

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o main .

FROM build-stage AS run-test-stage

RUN go test -v ./..

FROM gcr.io/distroless/base-debian11 AS build-release-stage

WORKDIR /

COPY --from=build-stage /auth-service /auth-service

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT [ "/auth-service" ]