version: '3.8'

services:
  auth-services:
    # image: vsarcher/auth-service:1.2
    build:
      context: auth-service
    env_file: .env
    ports:
      - 3000:3000
    command: air main.go -b 0.0.0.0
    depends_on:
      - postgres-db
    restart: always

  # forum-services:
  #   # image: vsarcher/forum-service:v1.0
  #   build:
  #     context: forum-service
  #   env_file: .env
  #   ports:
  #    - 5000:8080
  #   # volumes:
  #   #   - .:/app
  #   command: air main.go -b 0.0.0.0
  #   restart: always

  postgres-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-db:/var/lib/postgresql/data\
volumes:
  postgres-db:

# networks:
#   private:
#   public:
